version: '3.9'

networks:
  unity:
    driver: bridge

volumes:
  pgsql_db_data:

services:
  httpd:
    container_name: ${DOCKER_DOMAIN}-httpd
    image: ${DOCKER_DOMAIN}-php:8.3-apache
    restart: always
    build:
      context: ./docker
      dockerfile: Dockerfile_Httpd
    volumes:
      - ./:/var/www/html/
    ports:
      - ${DOCKER_HTTPD_PORT}:80
    networks:
      - unity

  pgsql:
    container_name: ${DOCKER_DOMAIN}-pgsql
    image: ${DOCKER_DOMAIN}-postgres:14.11
    build:
      context: ./docker
      dockerfile: Dockerfile_Pgsql
    restart: always
    shm_size: 128mb
    environment:
      - POSTGRES_USER=${DOCKER_PGSQL_USER}
      - POSTGRES_PASSWORD=${DOCKER_PGSQL_PASS}
    volumes:
      - pgsql_db_data:/var/lib/postgresql/data
    ports:
      - ${DOCKER_PGSQL_PORT}:5432
