FROM php:8.3-apache
LABEL authors=${DOCKER_AUTHOR}

RUN apt-get update -y

WORKDIR /var/www/html

COPY ../. .
COPY php/000-default.conf /etc/apache2/sites-available/000-default.conf
COPY php/php.ini /usr/local/etc/php/php.ini
#COPY php/php.ini /usr/local/etc/php/php.ini-development
#COPY php/php.ini /usr/local/etc/php/php.ini-production
COPY --from=composer:2.7.2 /usr/bin/composer /usr/bin/composer

RUN chown -R www-data:www-data /var/www/html

RUN a2enmod rewrite

ENTRYPOINT ["docker/php/entrypoint.sh"]
